    #------------------------#
    # Spherical PET Geometry 
    #------------------------#

    /gate/world/daughters/name sphericalPET
    /gate/world/daughters/insert sphere
    /gate/sphericalPET/geometry/setRmin           80. mm
    /gate/sphericalPET/geometry/setRmax           85. mm
    /gate/sphericalPET/setMaterial                Air
    /gate/sphericalPET/vis/setColor               white
    /gate/sphericalPET/vis/forceWireframe

    #------------------------#
    # Detector Crystal Module
    #------------------------#

    /gate/sphericalPET/daughters/name module
    /gate/sphericalPET/daughters/insert box
    /gate/module/geometry/setXLength 3 mm
    /gate/module/geometry/setYLength 3 mm
    /gate/module/geometry/setZLength 10 mm
    /gate/module/setMaterial Air
    /gate/module/vis/setColor green

    #------------------------#
    # Crystal inside Module
    #------------------------#

    /gate/module/daughters/name crystal
    /gate/module/daughters/insert box
    /gate/crystal/geometry/setXLength 3 mm
    /gate/crystal/geometry/setYLength 3 mm
    /gate/crystal/geometry/setZLength 10 mm
    /gate/crystal/setMaterial LYSO
    /gate/crystal/vis/setColor red

    
    /gate/crystal/attachCrystalSD

    #------------------------#
    # Repeat Crystals (Z-axis)
    #------------------------#

    /gate/crystal/repeaters/insert cubicArray
    /gate/crystal/cubicArray/setRepeatNumberX 1
    /gate/crystal/cubicArray/setRepeatNumberY 1
    /gate/crystal/cubicArray/setRepeatNumberZ 3
    /gate/crystal/cubicArray/setRepeatVector 0. 0. 10 mm

    #------------------------#
    # Place Modules (Phi and Theta sweep)
    #------------------------#

    /gate/module/repeaters/insert ring
    /gate/module/ring/setRepeatNumber 24
    /gate/module/ring/setFirstAngle 0 deg
    /gate/module/ring/setAngularSpan 360 deg

    /gate/module/repeaters/insert genericRepeater
    /gate/module/genericRepeater/setPlacementsFilename /home/gateuser/sim/polar_placements.txt




