/gate/world/daughters/name LungPhantom
/gate/world/daughters/insert ImageNestedParametrisedVolume


# READ IMAGE (.h33 for Interfile, .mhd for MetaImage, .hdr for Analyze)
/gate/LungPhantom/geometry/setImage AtnGate{SimuId}.h33
/gate/LungPhantom/geometry/validateImageFile true 


# INSERT THE TRANSLATOR THAT WILL CONVERT THE IMAGE FROM DIGITAL VALUES TO
# MATERIAL INFORMATION
# RANGE TRANSLATOR (label values)
/gate/LungPhantom/geometry/setRangeToMaterialFile AttenuationConv.dat

/gate/LungPhantom/placement/setTranslation 0. 0. 0. mm
/gate/LungPhantom/placement/setRotationAxis 1 0 0
/gate/LungPhantom/placement/setRotationAngle 0 deg

# 敏感探测器绑定
/gate/LungPhantom/attachPhantomSD


# ACTORS to get mu map
/gate/actor/addActor MuMapActor getMuMap
/gate/actor/getMuMap/attachTo LungPhantom
/gate/actor/getMuMap/save images/Phantom{SimuId}.hdr
/gate/actor/getMuMap/setVoxelSize 1.0 1.0 1.0  mm
/gate/actor/getMuMap/setResolution 128 128 128 #from 64 to 128
/gate/actor/getMuMap/setEnergy 511 keV
